### ISSUE TITLE
PHP Error?

### ISSUE THREAD

**Issue by Phedona** [kanalumaddela/k-load#51]
Hi!
Today I installed K-Load on a web server, but am I facing a problem with PHP?
Here is the following error code:
**Fatal error: require_once(): Failed opening required '/homepages/46/d947211115/htdocs/ukraine/web/vendor/autoload.php' (include_path='.:/usr/lib/php7.4') in /homepages/46/d947211115/htdocs/ukraine/web/index.php on line 20**

What could it be? I have it with php 7.3, 8.0, 8.1 and 8.4? Tried, but only with 7.4 comes this error, with other versions a 500 error

**Comment by kanalumaddela** [comment]
Note: this project is dated and the latest release will break on php 8. 

When downloading from GitHub, the vendor folder is not a sort of the project. That is performed with `composer install`. You need to have composer installed first, https://getcomposer.org/download/ .

You download the latest release https://github.com/kanalumaddela/k-load/releases/latest, unzip to web folder, run `composer install` and that should be it.
